### ISSUE TITLE
Quasar build error

### ISSUE THREAD

**Issue by doumlap** [paritosh149/quasar-ts#1]
Hi @paritosh149 !

I have looking for many days if it is possible to have all the power of quasar while using TS. I found out your repository on some quasar issue and wanted to give it a try. 

When running ```quasar build``` ive got this error =>
`ERROR in ./.quasar/entry.js
Module build failed:   TypeError: Cannot read property 'helpers' of undefined (While processing preset: "C:\\MyCode\\test\\quasar-ts\\n  ode_modules\\@vue\\babel-preset-app\\index.js")`

Do you have this error? Any idea why this happen? 

Also, you should add `"exclude": [
    "./node_modules/*"
  ]` within your tsconfig.json to make sure ts doesnt try to transpile any node_modules

Thank you

**Comment by paritosh149** [comment]
@doumlap , 
Let me clarify here that the repo was created for issue #64 [https://github.com/quasarframework/quasar-cli/issues/64](url). It is a work in progress. Currently, I am not contributing to it, but made it available, as is, on request. So, it won't work, As Is !
However, I understood your suggestion about the exclusion. Thanks

**Comment by doumlap** [comment]
Thank,

I did see this was for further work but i taugh this was a working solution. Do you think that ts support will come any time soon? From my part, its the only things missing so i can jump in and start my new app (electron) using it...

**Comment by paritosh149** [comment]
As it's evident in the earlier referred issue, I want TS support within Quasar-CLI. Hence, did my part and submitted the work to Quasar-CLI repo. Having said that, I am very hopeful that the next Quasar-CLI update will have TS support.

**Comment by doumlap** [comment]
I dont know about the CLI but ive seen somewhere that the next version (1.0.0) of quasar will include typescript support! Hoppefully this release is coming soon!
